source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  layout:
    hidden: true
  eleventyExcludeFromCollections:
    hidden: true
  draft:
    type: switch
  logo_image:
    empty_type: null
    comment: If an image is uploaded it will be used over a name set in the logo text field
  logo_text:
    comment: If an image is set in the logo image field, this value will not be used
_select_data: {}
_structures:
  content_blocks:
    style: select
    id_key: _bookshop_name
    values:
      - value:
          _bookshop_name: generic/sample
          text:
        label: Sample
        description:
        icon:
        tags: []
        _inputs: {}
_editables: {}

data_config:
  fonts: true

timezone: Etc/UTC
